# Generated by Django 5.2.8 on 2025-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('origin', models.CharField(choices=[('human', 'Human-written'), ('ai', 'AI-generated')], max_length=5)),
            ],
        ),
    ]
