# Generated by Django 5.2.8 on 2025-11-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Years of teaching experience in this field of study')),
                ('department', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('human', 'Human-written'), ('ai', 'AI-generated')], max_length=5)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('response_time', models.PositiveIntegerField(help_text='Time in milliseconds')),
                ('index', models.PositiveSmallIntegerField(help_text='Order of the text shown')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='study.participant')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.textitem')),
            ],
        ),
    ]
